name: Build Bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build binary
      run: go build -v -o rin-react-bot main.go
    
    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: rin-react-bot
        path: rin-react-bot
